site_name: KNULLI Wiki
site_url: https://knulli.org
repo_url: https://github.com/knulli-cfw/knulli.org
repo_name: knulli.org
copyright: Copyright Creative Commons Attribution-ShareAlike 4.0 International
theme:
  name: material
  logo: _inc/images/logo-knulli.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: art-book
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: art-book-next
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Oxygen
    code: Oxygen Mono
  features:
    - navigation.top
    #- navigation.instant
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - search.suggest
    - content.tooltips
    - content.code.copy
    - content.code.annotate
  custom_dir: overrides
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 3
      permalink: ¶
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
extra_css:
  - _inc/css/custom.css
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/knulli-cfw/distribution
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/HXPS3DAeeB
  extra:
    alternate:
      - name: English
        link: /en/ 
        lang: en
      - name: Español
        link: /es/
        lang: es
      - name: Deutsch
        link: /de/
        lang: de
      - name: Polski
        link: /pl/
        lang: pl
      - name: Türkçe
        link: /tr/
        lang: tr
      - name: Português do Brasil
        link: /pt-BR/
        lang: pt-BR
      - name: Italiano
        link: /it/ 
        lang: it
plugins:
  - search:
      lang: [en, es, de, pl, tr, it] # Removed pt-BR here to stop the warning
  - glightbox
  - macros:
      include_dir: includes
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: es
          name: Español
          build: true
          nav:
            - Inicio: index.md
            - Acerca de KNULLI: about-knulli.md
            - Preguntas Frecuentes:
                - Preguntas Frecuentes: faq/index.md
                - Preguntas sobre KNULLI: faq/knulli.md
                - Solución de Problemas: faq/troubleshooting.md
            - Jugar:
                - Guía de Inicio Rápido: play/quick-start.md
                - Instalar KNULLI: play/install.md
                - Añadir Juegos:
                    - Añadir Juegos: play/add-games/index.md
                    - Almacenamiento de los Juegos: play/add-games/game-storage.md
                    - Formatear: play/add-games/formatting.md
                    - Segunda Tarjeta SD: play/add-games/second-sd-card.md
                    - Transferencia de Red: play/add-games/network-transfer.md
                    - Acceso por USB: play/add-games/accessing-via-usb.md
                    - Acceso a la Tarjeta SD: play/add-games/accessing-sd-card.md
                - BIOS: play/bioses.md
                - Scraping: play/scraping.md
                - Métodos de Entrada: play/basic-inputs.md
                - Atajos: play/hotkey-shortcuts.md
                - Configuración de los Juegos: play/game-settings.md
                - Logros: play/retro-achievements.md
                - Juego en Red: play/netplay.md
                - Actualizar: play/update.md
            - Configuración:
                - Redes: configure/networking.md
                - Reanudación Rápida: configure/quick-resume.md
                - Bluetooth: configure/bluetooth.md
                - Controles: configure/controls.md
                - Colecciones: configure/collections.md
                - Juegos Multidisco: configure/multi-disc-games.md
                - LEDs RGB: configure/rgb-leds.md
                - Administración de Energía: configure/power-management.md
                - Personalización:
                    - Personalización: configure/customization/index.md
                    - Temas: configure/customization/themes.md
                    - Música de Fondo: configure/customization/background-music.md
                    - Marcos: configure/customization/bezel-decorations.md
                    - Imagen de Inicio: configure/customization/bootlogo.md
                    - Filtros: configure/customization/shaders.md
                - SSH: configure/ssh.md
                - Retroarch:
                    - Controles: configure/retroarch/controls.md
                    - Atajos Personalizados: configure/retroarch/custom-hotkey-shortcuts.md
                - PPSSPP:
                    - Trucos: configure/ppsspp/cheats.md
                    - Multijudador: configure/ppsspp/multiplayer.md
                - Reinicio de Fábrica: configure/reset-to-factory-settings.md
                - Parchar y Sobreescribir: configure/patches-and-overlays.md
            - Sistemas:
                - Pico-8: systems/pico-8.md
                - PortMaster: systems/portmaster.md
                - ScummVM: systems/scummvm.md
                - Reproductor Multimedia: systems/media-player.md
                - Herramientas:
                    - OD Commander: systems/tools/od-commander.md
            - Guías:
                - Migración a Doble Tarjeta SD: guides/dual-sd-card-migration.md
                - Actualizaciones Mayores: guides/major-updates.md
                - Particionado: guides/partitioning.md
                - PortMaster y exFAT: guides/portmaster-and-exfat.md
                - Sincronización: guides/syncthing.md
                - Extraer Firmware:
                    - A133: guides/firmware-extraction/A133-firmware-extract.md
                    - H700: guides/firmware-extraction/h700-firmware-extract.md
            - Desarrollo:
                - Compilar KNULLI con Docker: development/building-knulli-with-docker.md
            - Comunidad:
                - Contribuir: community/contribute.md
            - Dispositivos: devices/index.md
        - locale: de
          name: Deutsch
          build: true
          nav:
            - Start: index.md
            - Über KNULLI: about-knulli.md
            - Häufige Fragen:
                - Häufige Fragen: faq/index.md
                - Fragen zu KNULLI: faq/knulli.md
                - Problemlösungen: faq/troubleshooting.md
            - Spielen:
                - Schnellstartanleitung: play/quick-start.md
                - Installation: play/install.md
                - Spiele hinzufügen:
                    - Spiele hinzufügen: play/add-games/index.md
                    - Speicherort für Spiele: play/add-games/game-storage.md
                    - Formatieren: play/add-games/formatting.md
                    - Zweite SD-Karte: play/add-games/second-sd-card.md
                    - Netzwerkübertragung: play/add-games/network-transfer.md
                    - Zugriff via USB: play/add-games/accessing-via-usb.md
                    - Zugriff auf SD-Karte: play/add-games/accessing-sd-card.md
                - BIOSes: play/bioses.md
                - Scraping: play/scraping.md
                - Tasten und Funktionen: play/basic-inputs.md
                - Tastenkombinationen: play/hotkey-shortcuts.md
                - Spieleinstellungen: play/game-settings.md
                - Achievements: play/retro-achievements.md
                - Netplay: play/netplay.md
                - Aktualisieren: play/update.md
            - Konfiguration:
                - Netzwerkverbindungen: configure/networking.md
                - Quick Resume: configure/quick-resume.md
                - Bluetooth: configure/bluetooth.md
                - Controller: configure/controls.md
                - Spielesammlungen: configure/collections.md
                - Spiele mit mehreren CDs: configure/multi-disc-games.md
                - RGB LEDs: configure/rgb-leds.md
                - Energieeinstellungen: configure/power-management.md
                - Personalisieren:
                    - Personalisieren: configure/customization/index.md
                    - Themes: configure/customization/themes.md
                    - Hintergrundmusik: configure/customization/background-music.md
                    - Bezel-Dekorationen: configure/customization/bezel-decorations.md
                    - Bootlogo: configure/customization/bootlogo.md
                    - Shaders: configure/customization/shaders.md
                - SSH: configure/ssh.md
                - Retroarch:
                    - Controller: configure/retroarch/controls.md
                    - Benutzerdefinierte Tastenkombinationen: configure/retroarch/custom-hotkey-shortcuts.md
                - PPSSPP:
                    - Cheats: configure/ppsspp/cheats.md
                    - Multiplayer: configure/ppsspp/multiplayer.md
                - Werkseinstellungen: configure/reset-to-factory-settings.md
                - Patches und Overlays: configure/patches-and-overlays.md
            - Systeme:
                - Pico-8: systems/pico-8.md
                - PortMaster: systems/portmaster.md
                - ScummVM: systems/scummvm.md
                - Media Player: systems/media-player.md
                - Werkzeuge:
                    - OD Commander: systems/tools/od-commander.md
            - Anleitungen:
                - Zu Dual-SD-Card-Setup wechseln: guides/dual-sd-card-migration.md
                - Umfangreiche Updates: guides/major-updates.md
                - Partitionieren: guides/partitioning.md
                - PortMaster und exFAT: guides/portmaster-and-exfat.md
                - Syncthing: guides/syncthing.md
                - Firmware Extraction:
                    - A133: guides/firmware-extraction/A133-firmware-extract.md
                    - H700: guides/firmware-extraction/h700-firmware-extract.md
            - Entwicklung:
                - KNULLI mit Docker bauen: development/building-knulli-with-docker.md
            - Gemeinschaft:
                - Unterstützen: community/contribute.md
            - Geräte: devices/index.md
        - locale: pl
          name: Polski
          build: true
          nav:
            - Strona główna: index.md
            - FAQs: faq/index.md
            - Graj:
                - Instalacja: play/install.md
                - Dodaj gry: play/add-games/index.md
                - Osiągnięcia: play/retro-achievements.md
            - Sterowanie: configure/controls.md
            - Urządzenia: devices/index.md
        - locale: tr
          name: Türkçe
          build: true
          nav:
            - Anasayfa: index.md
            - FAQs: faq/index.md
            - Oyna:
                - Kurulum: play/install.md
                - Oyun Ekleme: play/add-games/index.md
                - Başarımlar: play/retro-achievements.md
                - Ağ Oyunu Desteği: play/netplay.md
            - Kontroller: configure/controls.md
            - Cihazlar: devices/index.md
        - locale: pt-BR
          name: Português do Brasil
          build: true
          nav:
            - Início: index.md
            - Sobre o KNULLI: about-knulli.md
            - Perguntas Frequentes:
                - Perguntas Frequentes: faq/index.md
                - Solução de Problemas: faq/troubleshooting.md
            - Jogar:
                - Guia rápido: play/quick-start.md
                - Instalação: play/install.md
                - Adicionar Jogos:
                    - Adicionar Jogos: play/add-games/index.md
                    - Armazenamento dos Jogos: play/add-games/game-storage.md
                    - Formatando: play/add-games/formatting.md
                    - Segundo Cartão SD: play/add-games/second-sd-card.md
                    - Transferência via Rede: play/add-games/network-transfer.md
                    - Acessando o Cartão SD: play/add-games/accessing-sd-card.md
                - Atalhos: play/hotkey-shortcuts.md
                - Conquistas: play/retro-achievements.md
                - Atualizar: play/update.md
            - Configuração:
                - Rede: configure/networking.md
                - Controles: configure/controls.md
                - Coleções: configure/collections.md
                - Molduras: configure/customization/bezel-decorations.md
                - Temas: configure/customization/themes.md
            - Sistemas: systems/media-player.md
            - Dispositivos: devices/index.md
        - locale: it
          name: Italiano
          build: true
          nav:
            - Inizio: index.md
            - Info su KNULLI: about-knulli.md
            - Domande Frequenti:
                - Domande Frequenti: faq/index.md
                - Risoluzione dei problemi: faq/troubleshooting.md
            - Giocare:
                - Guia Rapida: play/quick-start.md
                - Installazione: play/install.md
                - Aggiungere Giochi:
                    - Aggiungere Giochi: play/add-games/index.md
                    - Archiviazione dei Giochi: play/add-games/game-storage.md
                    - Formattare: play/add-games/formatting.md
                    - Seconda Scheda SD: play/add-games/second-sd-card.md
                    - Trasferimento via Rete: play/add-games/network-transfer.md
                    - Accesso alla Scheda SD: play/add-games/accessing-sd-card.md
                - Scorciatoie: play/hotkey-shortcuts.md
                - Achievements: play/retro-achievements.md
                - Aggiornare: play/update.md
            - Configurazione:
                - Rete: configure/networking.md
                - Controlli: configure/controls.md
                - Collezioni: configure/collections.md
                - Decorazioni: configure/customization/bezel-decorations.md
                - Temi: configure/customization/themes.md
            - Sistema: systems/media-player.md
            - Dispositivo: devices/index.md
nav:
    - Home: index.md
    - About KNULLI: about-knulli.md
    - FAQs:
      - FAQs: faq/index.md
      - Questions about KNULLI: faq/knulli.md
      - Troubleshooting: faq/troubleshooting.md
    - Play:
      - Quick Start Guide: play/quick-start.md
      - Install: play/install.md
      - Add Games:
        - Add Games: play/add-games/index.md
        - Game Storage: play/add-games/game-storage.md
        - Formatting: play/add-games/formatting.md
        - Second SD Card: play/add-games/second-sd-card.md
        - Network Transfer: play/add-games/network-transfer.md
        - Accessing via USB: play/add-games/accessing-via-usb.md
        - Accessing SD Card: play/add-games/accessing-sd-card.md
      - BIOSes: play/bioses.md
      - Scraping: play/scraping.md
      - Basic Inputs: play/basic-inputs.md
      - Hotkey Shortcuts: play/hotkey-shortcuts.md
      - Game Settings: play/game-settings.md
      - Achievements: play/retro-achievements.md
      - Netplay: play/netplay.md
      - Update: play/update.md
    - Configure:
      - Networking: configure/networking.md
      - Quick Resume: configure/quick-resume.md
      - Bluetooth: configure/bluetooth.md
      - Controls: configure/controls.md
      - Collections: configure/collections.md
      - Multi-Disc Games: configure/multi-disc-games.md
      - RGB LEDs: configure/rgb-leds.md
      - Power Management: configure/power-management.md
      - Customization:
        - Customization: configure/customization/index.md
        - Themes: configure/customization/themes.md
        - Background Music: configure/customization/background-music.md
        - Bezel Decorations: configure/customization/bezel-decorations.md
        - Boot Logo: configure/customization/bootlogo.md
        - Shaders : configure/customization/shaders.md
      - SSH: configure/ssh.md
      - Retroarch:
        - Controls: configure/retroarch/controls.md
        - Custom Hotkey Shortcuts: configure/retroarch/custom-hotkey-shortcuts.md
      - PPSSPP:
        - Cheats: configure/ppsspp/cheats.md
        - Multiplayer: configure/ppsspp/multiplayer.md
      - Factory Settings: configure/reset-to-factory-settings.md
      - Patches and Overlays: configure/patches-and-overlays.md
    - Systems:
      - Pico-8: systems/pico-8.md
      - PortMaster: systems/portmaster.md
      - ScummVM: systems/scummvm.md
      - Media Player: systems/media-player.md
      - Tools:
          - OD Commander: systems/tools/od-commander.md
    - Guides:
        - Dual SD Card Migration: guides/dual-sd-card-migration.md
        - Major Updates: guides/major-updates.md
        - Partitioning: guides/partitioning.md
        - PortMaster and exFAT: guides/portmaster-and-exfat.md
        - Syncthing: guides/syncthing.md
        - Firmware Extraction:
            - A133: guides/firmware-extraction/A133-firmware-extract.md
            - H700: guides/firmware-extraction/h700-firmware-extract.md
    - Development:
        - Building KNULLI With Docker: development/building-knulli-with-docker.md
    - Community:
        - Contribute: community/contribute.md
    - Devices: 
      - devices/index.md
      - Anbernic:
        - RG-Arc-S: devices/anbernic/rg-arc-s.md
        - RG28XX: devices/anbernic/rg28xx.md
        - RG34XX: devices/anbernic/rg34xx.md
        - RG35XX Original: devices/anbernic/rg35xx.md
        - RG35XX Plus: devices/anbernic/rg35xx-plus.md
        - RG35XX H: devices/anbernic/rg35xx-h.md
        - RG35XX 2024: devices/anbernic/rg35xx-2024.md
        - RG35XX SP: devices/anbernic/rg35xx-sp.md
        - RG40XX H: devices/anbernic/rg40xx-h.md
        - RG40XX V: devices/anbernic/rg40xx-v.md
        - RGCubeXX: devices/anbernic/rgcubexx.md
      - GoRetroid:
        - Retroid Pocket 5: devices/goretroid/retroid-pocket-5.md
        - Retroid Pocket Mini: devices/goretroid/retroid-pocket-mini.md
      - Orange Pi Zero 2w:
        - Orange Pi Zero 2w: devices/orange-pi/orange-pi-zero-2w.md
      - Powkiddy:
        - RGB30: devices/powkiddy/rgb30.md
        - X55: devices/powkiddy/x55.md
      - TrimUI:
        - Brick: devices/trimui/brick.md
        - Smart Pro: devices/trimui/smart-pro.md
